retorquere/zotero-better-bibtex

- chrome/content/zotero-better-bibtex/schomd.coffee
Fixes indentation error in `schomd.search`
> Fixed indentation in schomd.search

- chrome/content/zotero-better-bibtex/bulk-clear-confirm.xul
- chrome/content/zotero-better-bibtex/keymanager.coffee
Add a title and center the dialog
> Prettier generate/clear keys confirm dialog

- chrome/content/zotero-better-bibtex/preferences.xul
> Correct association of folding preference.

- chrome/content/zotero-better-bibtex/preferences.xul
I haven't tested it though (as I can't run bbt straight from the git checkout ) but that's pretty straightforward.
> Allow state of columns in export list to persist

- test/fixtures/export/Export of creator-type fields from embedded CSL variables #365.bib
for all videos, change author to director
> Update Export of creator-type fields from embedded CSL variables #365.bib

- test/fixtures/export/Export of creator-type fields from embedded CSL variables #365.csl.json
> Update Export of creator-type fields from embedded CSL variables #365.csl.json

- test/fixtures/export/Export of creator-type fields from embedded CSL variables #365.json
add "programTitle": "Friends",
> Update Export of creator-type fields from embedded CSL variables #365.json

- chrome/content/zotero-better-bibtex/cayw.coffee
- chrome/content/zotero-better-bibtex/schomd.coffee
- chrome/content/zotero-better-bibtex/web-endpoints.coffee
* cayw.coffee: refactoring, use getStyle function call, supports
Juris-M styles.
* schomd.coffee: improvements to bbl output format, refactoring of web
endpoint calls.
* web-endpoints.coffee: Add new calls
> Latest changes to support TeXmacs integration.

- docs/cayw.md
Opening pull request as per gitter exchange.
> Document command parameter for latex CAYW format

- content/cayw/formatter.ts
- docs/cayw.md
Opening as per gitter exchange.
> Add biblatex CAYW format

- locale/pt-BR/zotero-better-bibtex.dtd
- locale/pt-BR/zotero-better-bibtex.properties
Subject says it all :) . If anything else needs to be done regarding this, please let me know.
> Add Brazilian Portuguese translation (pt-BR)

- content/Preferences.xul
Minor details as discussed in recent issues.
> More info on quality reports

- site/content/exporting/pandoc.md
Related to https://github.com/retorquere/zotero-better-bibtex/issues/2070.
> Add paragraph about LibreOffice support to DOCX

- site/content/support/faq.md
Related to issue #2628
No worries if you consider this unnecessary, but it would have saved me some time and so maybe, it will help somebody else, too.
> Differentiate JabRef settings more clearly in faq.md

- content/json-rpc.ts
This PR surfaces Zotero's advanced search functionality through json-rpc. E.g.:
```
{
"jsonrpc": "2.0",
"method": "item.advancedsearch",
"params": [[["dateModified", "isAfter", "2023-08-30 09:09:09"]], 1]
}
```
The first paramater is an array of conditions that get applied like so:
```
for (const [name, operator, value] of params) {
search.addCondition(name, operator, value)
}
```
I'm not sure if this is the right way to go about this, so let me know if something is off or if I've missed anything.
> Add item.advancedsearch json-rpc method

- content/json-rpc.ts
Image annotations are only cached to disk when a PDF is opened for the first time (eg, after syncing between devices). So occasionally `annotationImagePath` will be populated with the correct path to the image when calling `item.attachments`, but the image won't exist on disk. The PR ensures these images are created in this case.
> Ensure item.attachments renders missing image annotations

- content/json-rpc.ts
Allow to open a PDF in zotero client.
> feat(): add viewer.viewPDF on JSON-RPC

- content/json-rpc.ts
item.search function has been simplified, eliminating some string manipulation (that can be eventually done on the "client" side).
The condition ('citationKey', 'contains', value) has been removed, since it was a too strong constrain.
The item.search accepts now a vector of tuple with 1 to 4 elements, as expected.
Other behaviors, previously present, has been deactivated, and some custom actions have been created to easily use them.
The library argument has been removed, since it is a special case for conditions.
> refactor!: item.search for json rpc works

- content/json-rpc.ts
This implements some of the feedback left for #2723
> JSON-RPC: Support library id with basic string search

- README.md
Hi thanks for this helpful plugin! It seems https://github.com/retorquere/zotero-better-bibtex/issues/2829 says "... has been resolved", thus removing it to save a dozen seconds for future readers to see what is going on :)
> Super tiny update README for Zotero 7 status

- site/content/installation/_index.md
Adjust the term to 'Plugins' to accurately reflect Zotero 7.
> Adjust the term to 'Plugins' to accurately reflect Zotero 7.
