retorquere/zotero-better-bibtex

chrome/content/zotero-better-bibtex/BetterBibTeXPatternFormatter.coffee
This is just a small feature enhancement, which adds a substring filter for creating BibTeX keys. It takes two arguments x and y and returns the substring of length y starting at position x of the input string.
=> New substring filter for custom BibTeX keys

resource/translators/Better BibLaTeX.coffee
Zotero's Bill and Statute types are @legislation in BibLaTeX.
=> Fix typo stature->statute (zotero item type)

chrome/content/zotero-better-bibtex/cayw.coffee
I think this is the cause of ZotPlus/zotero-citations#11
=> Typo: schmd -> schomd

chrome/content/zotero-better-bibtex/db.coffee
“Keep My Current Cache” / “Reset My Cache”
instead of
“OK” / “Cancel”
This issue references attempts to make a clearer cache-drop message: https://github.com/ZotPlus/zotero-better-bibtex/commit/9f3c4aebd642fd3f8a9bbff639bc1ac5908b846c#commitcomment-15176704
=> Clarify button labels for cache reset dialog

chrome/content/zotero-better-bibtex/schomd.coffee, chrome/content/zotero-better-bibtex/web-endpoints.coffee
These changes are tested and working.
I added the guard in the text_escape that we discussed, to remove the extraneous string "undefined" that would appear in the bbl output. I don't know why it did not appear in the corresponding markdown output, but added it anyway just to be sure. It occurs in the HTML output prototype in citeproc.js; in fact, that's where I learned it from.
I modified the way that the style file is located so that Juris-M styles such as jm-babyblue are found by it. Without that, it can not find them, since they have a different base URL. Actually, the Juris-M code did not have it's own style ID base URL's in it either; I've made a patch for that that I hope they accept. If the short URL does not work, try passing the entire thing, including the …
=> New jsonrpc endpoints for bibliographyhtml and bibliographybbl

chrome/content/zotero-better-bibtex/cayw.coffee, resource/tests/export.feature
Incorporate the change proposed in #358 and implemented in 8b260cb to CAYW as well.
=> Also omit square brackets for Pandoc Citation in CAYW

content/Preferences.xul, locale/en-US/zotero-better-bibtex.dtd
Hello, and my apologies up-front for nit-picking here ;-)
Because the `U` in `URL` stands in for [uniform](https://en.wiktionary.org/wiki/uniform#English), and that is spoken with a `j`-like consonant sound, the common rule "an before vowels" doesn't match here. Many English words starting with `u` are exceptions here. A true example would be "an [Up Goer Five](https://xkcd.com/1133/)" ;-D
Nonetheless: 1k thanks for this neat add-on!
=> correct grammar, based on spoken sound

content/Preferences.ts, content/Preferences.xul, locale/en-US/zotero-better-bibtex.dtd
It conceptually fits there well. I tried having a separator between the checkbox and the "Abbreviation style:" label and listbox, but thought that this looked better.
=> Move journal abbreviations to Export tab

content/key-manager/formatter.ts
According to the documentation, the `authshort` key is supposed to give
> The last name if one author is given; the first character **of up to three authors’ last names** if more than one author is given. A plus character is added, if there are more than three authors.
This is also reflected in the comment in line 326 of the modified file. However, the current implementation gives first characters for all authors, and then adds a plus if there were more than three of them.
To reproduce this bug: My configuration is `[authshort:nopunct][shortyear]`; a paper by authors Alpha, Beta, Gamma, Delta receives the key `ABGD+18`, whereas the expected behavior would be `ABG+18`.
Based on the surrounding code, I expect this pull request to fix the bug. However, I failed at building the plugin, and …
=> Do not use more than three initials in case of authshort key

pandoc/Makefile, pandoc/pandoc-zotero-live-citemarkers.lua
```
commit c6b62dfc8f4a09e8a44ba83cd119934354bc5e10
Author: Jambunathan K <kjambunathan@gmail.com>
Date:   Thu Jul 30 15:36:51 2020 +0530
zotero.lua: Add support for generating transferable live ODT document
* pandoc/pandoc-zotero-live-citemarkers.lua (config): New field
`transferable'.
(Meta): Set `config.style' from metadata variable
`zotero_transferable'.  Update meta.xml, only if the doc is
non-transferable.
(zotero_docpreferences_odt, zotero_bibl_odt_banner): New
functions.
(zotero_bibl_odt, zotero_ref): Handle `config.transferable'.
(Doc): Transferable documents require a banner (and document
preferences) right at the beginning of body text.
* pandoc/Makefile (ZOTERO_TRANSFERABLE): New variable.
(odt-scannable-cite.odt, odt-with-csl-style.odt)
(odt-without-csl-style.odt): Use above …
```
=> zotero.lua: Add support for generating transferable live ODT document

translators/bibtex/reference.ts
With this, `item.arXiv.source` will only depend on values in Zotero's Publication and Extra fields.
=> arXiv source

translators/Better BibTeX Citation Key Quick Copy.ts
First time contributor here. Roam Research is gaining traction in the academic community and some importers already exist which let you create pages using better bib text cite keys ([see here](https://github.com/melat0nin/zotero-roam-export)).
In roam a page is referenced using [[@PAGETITLE]]. I implemented a simple roam cite key option which maps items to their better bib tex keys.
If there is a way to contribute this functionality without hard coding it i.e. through the string-template option I see here then I would be happy to use an alternative.
=> Add cite key option to support roam references

site/content/citing/_index.md
As I'm currently using APA 7th edition, I extensively utilize Zotero's "cheater syntax" to define the `tex.shortauthor` in the extra field. After reading #149, I spent some time designing a citekey pattern that uses the `tex.shortauthor` if present and defaults to `[auth:lower]` if not:
```
[Extra:transliterate:replace=(?\:tex\\.shortauthor\[\:\=\]\\s+(\\w+))|.*,$1,regex:clean:lower][>0][year] | [auth:lower][year]
```
I admit, using a regex replace is not very elegant, but it works, and maybe it is useful for others. Hence, the PR to include it in the documentation.
EDIT: Just after this PR, I noticed that when using the previous pattern sometimes $1 referred to the whole input/extra field. This issue is now fixed simplifying the pattern but now requiring a clean after the replace.
=> Add citekey pattern using the tex.shortauthor extra field with [auth:lower] fallback to docs

translators/bibtex/unicode_translator.ts
Can be useful for code names in paper titles
=> Add <tt> -- \texttt{} translation

site/content/citing/aux-scanner.md
Should resolve https://github.com/retorquere/zotero-better-bibtex/discussions/1918
I think I got the link to the higher-level [citation keys website](https://retorque.re/zotero-better-bibtex/citing/) correct, but it may need fixing.
=> Add AUX scanner documentation

content/Preferences/export/quickcopy.pug, locale/de-DE/zotero-better-bibtex.dtd, locale/en-US/zotero-better-bibtex.dtd, locale/fr-FR/zotero-better-bibtex.dtd, locale/pt-BR/zotero-better-bibtex.dtd, site/content/installation/preferences/export.md, test/features/steps/bbtjsonschema.json, test/features/steps/preferences.json, translators/Better BibTeX Citation Key Quick Copy.ts
- New citation export format of the form `cite:&key` and multiple keys of the form `cite:&key1;&key2;&key3`. 
- Added appropriate references wherever I found `orgref` mentioned. 
- Tested locally.
* `translators/Better BibTeX Citation Key Quick Copy.ts`: new logic for org-ref v3
=> Support for org-ref v3

content/json-rpc.ts
Hello,
I'm working on [MonsterWriter](https://www.monsterwriter.app/) and try to integrate the Zotero Desktop version into the app.
This change would be needed, so I could base the integration on better-bibtex.
See related issue https://github.com/retorquere/zotero-better-bibtex/issues/1941.
=> Extend RPC interface to list all collections

content/json-rpc.ts
This PR includes Zotero's native PDF annotations with an item's attachments using the `item.attachments` endpoint.
Example output:
```json
{
"jsonrpc": "2.0",
"result": [
{
"open": "zotero://open-pdf/library/items/K254PIHU",
"path": "/Users/****/Cockell and Herrera - 2008 - Why are some microorganisms boring.pdf",
"annotations": [
{
"key": "WK35324J",
"version": 0,
"itemType": "annotation",
"parentItem": "K254PIHU",
"annotationType": "highlight",
"annotationAuthorName": "",
"annotationText": "Why are some microorganisms boring?",
"annotationComment": "",
"annotationColor": "#80ff80",
"annotationPageLabel": "101",
"annotationSortIndex": "00000|000000|00073",
"annotationPosition": {
"pageIndex": 0,
"rects": [[42.52, 694.323, 562.481, 720.014]]
},
"tags": [],
"relations": {},
"dateAdded": …
```
=> JSON-RPC: Include annotations with attachments

content/json-rpc.ts
This PR continues where #2141 left off (cc: @argenos).
Examples:
Input:
```
{
"jsonrpc": "2.0",
"method": "item.collections",
"params": [
["eckerbridges2020"]
]
}
```
Output:
```
{
"jsonrpc": "2.0",
"result": {
"eckerbridges2020": [
{
"key": "X6J3CF6X",
"name": "Ecker",
"parentCollection": "32TAEIAY"
}
]
},
"id": null
}
```
---
Input (with `includeParents`)
```
{
"jsonrpc": "2.0",
"method": "item.collections",
"params": [
["eckerbridges2020"],
true
]
}
```
Output
```
{
"jsonrpc": "2.0",
"result": {
"eckerbridges2020": [
{
"key": "X6J3CF6X",
"name": "Ecker",
"parentCollection": {
"key": "32TAEIAY",
"name": "Research Essay",
"parentCollection": {
"key": "JR7798II",
"name": "Inquiry and Research",
"parentCollection": {
"key": "64BYQ89G",
"name": "BA",
"parentCollection": {
"key": "QV77LVKB", …
```
=> Add JSON-RPC endpoint to return item collections

content/translators.ts
The latest update introduced an error when using JSON-RPC `item.export`:
Input:
```
{
"jsonrpc" : "2.0",
"method" : "item.export",
"params" : [["magee2021"], "36a3b0b5-bad0-4a04-b79b-441c7cef77db"]
}
```
Output:
```
{
"jsonrpc": "2.0",
"error": {
"code": -32603,
"message": "TypeError: displayOptions2 is null"
},
"id": null
}
```
This PR adds support for the case when `null` is used for `displayOptions` eg:
```
Translators.exportItems(Translators.getTranslatorId(translator), null, { type: 'items', items: await getItemsAsync(found.map(key => key.itemID)) })
```
=> Handle case of null displayOptions

content/key-manager/formatter.ts
Using .join('.') instead of .join(sep) leads to all authors except the first one having a '.' after their surname initials. This commit corrects it to use the defined sep parameter.
Solves Issue #2238 
Note: The resulting src is untested.
=> Replace '.' with sep in authorIni

site/content/exporting/scripting.md
I had to update the script I used following https://github.com/retorquere/zotero-better-bibtex/issues/518#issuecomment-310522601, so thought it would be good to add it to the examples.
=> Add CSL JSON example to scripting.md

content/ZoteroPane.ts
The mapping required individual fields to be separated by not just by a comma, but by comma with whitespace on both sides. As a result, even the example given in the [documentation](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#patchdates)
```
date-added = dateAdded, timestamp=dateModified
```
did not work. This fix changes the regular expression so that whitespace before and after the comma is optional.
=> Less strict parsing of patchDates mapping config

content/json-rpc.ts
This PR fixes an issue where `item.attachments` was throwing an error for items that had non-PDF attachments. It simply adds an `isPDFAttachment()` check before attempting to access annotations.
=> Only access annotations for PDF attachments

content/json-rpc.ts
@retorquere Is there any harm in removing this check/error? I've added better support for groups libraries in https://github.com/mgmeyers/obsidian-zotero-integration , but I did so by always passing along the library id to the rpc endpoints. This works for users where `keyScope === 'library'` but not `keyScope === 'global'`. It seems to make sense to me to just ignore the library ID when `keyScope` is `global`, but I might be missing something.
Alternatively, is there a way to check a user's `keyScope` setting via cayw/json-rpc? Maybe we could return it along with the output of `user.groups`? That could be another solution to this issue.
=> Ignore libraryID instead of throwing an error when keysope is global

pandoc/pandoc-zotero-live-citemarkers.lua
Currently, if I run zotero.lua script against old pandoc version (e.g. 2.12) I get the following error message:
```
./zotero.lua:15: attempt to index a nil value (global 'lpeg')
stack traceback:
./zotero.lua:15: in function <./zotero.lua:11>
[C]: in function 'require'
./zotero.lua:1727: in main chunk
```
This is misleading. The pandoc version check exists in code, but doesn't seem to work.
This commit fixes the issue. Now I get proper error message when running with old pandoc.
The conversion is still running fine with newer pandoc. Tested on Windows.
=> Fix misleading error when running zotero.lua against old pandoc version

content/create-element.ts
Every time something calls `Elements#create()`, the new element gets added to `Elements.all`. Elements are only removed from that set when `Elements.removeAll()` or `Elements#remove()` is called.
That would be totally fine if the elements created by that method stuck around in the DOM until Zotero shut down / the plugin was disabled, but that's not the case much of the time. For instance, the [`buildItemContextMenu()` and `buildCollectionContextMenu()`  patches](https://github.com/retorquere/zotero-better-bibtex/blob/ec6ae3e169245d76ff18e9004cd7f03f2a9e6a4d/content/ZoteroPane.ts#L81) append 20+ elements to a submenu which is removed and recreated each time the methods are called. Because the old removed elements are still in `Elements.all`, they can never be garbage collected, and neither …
=> Fix memory leak in Elements

site/content/citing/_index.md
The sentence about dynamic keys seemed wrong (and there was a missing "in").
=> Fixed ambiguous sentence about dynamic vs fixed keys

site/content/support/faq.md
Just a small typo in the word "converted".
=> Fix typo in README.md

content/key-manager/formatter.ts
It took me some time to figure out the exact regex syntax, so I thought it could be worth mentioning in the docs since there are so many different regex implementation in different languages. It also seems like the syntax has changed somewhat and no longer requires the backslashes mentioned in https://github.com/retorquere/zotero-better-bibtex/issues/1933#issuecomment-973360959). 
Maybe there could also be a section somewhere in the docs with more advanced examples? E.g. I use the following to include only one author if there is only one, and if there is more than one I include first and last author:
```js
(
authorsn(sep=';').replace(/[^;]/g, '').len('>',0)
? authorLast.lower.postfix("\_")+auth.lower.postfix("\_")
: auth.lower.postfix("\_")
)
+year.postfix("\_") …
```
=> Include example of regex syntax

content/json-rpc.ts
An old script returned an error saying a citekey could not be found, my usage according to the site documentation appeared to be correct https://retorque.re/zotero-better-bibtex/exporting/json-rpc/index.html#itemattachmentscitekey
The documentation is missing the optional secondary parameter.
=> Fix item.attachments documentation

content/json-rpc.ts
Pretty straightforward, just had to remove the `isPDFAttachment` check.
=> JSON-RPC.attachments: Return epub and snapshot annotations

site/content/citing/cayw.md
In newer versions of Vim, there is a new configuration language called `vim9script`, which has some advantages over the "legacy vimscript" used in previous versions of Vim and Neovim (e.g. better readability and JIT compilation). Users that have written their `vimrc` in `vim9script` would also want to configure the Zotero/BetterBibTeX integration in that language.
This pull request provides a `vim9script` translation of the currently documented legacy vimscript solution.
(Neovim users likely want a corresponding Lua translation instead, but that is a separate issue.)
=> Documented Vim9 citation integratation

content/json-rpc.ts
Hello,
I started getting errors with retrieving annotations with Items that have multiple attachments that include a non file attachment e.g. a pubmed abstract
This is the error.
code: -32603
message:  "Error: getAnnotations() can only be called on file attachments"
Zotero 7 appears to stubbornly error out if you call getAnnotations on a non file attachment e.g. pubmed abstract or link, note etc.
I believe the isPDF check removed recently in pull request 2936 may have caused this problem.
https://github.com/retorquere/zotero-better-bibtex/pull/2936/files
I have replaced the isPDFAttachment this time with isFileAttachment to include the new epub and html attachments in Zotero 7.
Another approach is to catch an error in a try catch manner, maybe you think it is better this way.
Please check …
=> Fix annotation retrieval error potentially caused by pull request 2936
